// Code generated by "stringer -type=Operator -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNoop-0]
	_ = x[OpReturn-1]
	_ = x[OpAdd-2]
	_ = x[OpAddInt-3]
	_ = x[OpAddFloat-4]
	_ = x[OpAddArray-5]
	_ = x[OpAddBool-6]
	_ = x[OpSub-7]
	_ = x[OpSubInt-8]
	_ = x[OpSubFloat-9]
	_ = x[OpSubBool-10]
	_ = x[OpMul-11]
	_ = x[OpMulInt-12]
	_ = x[OpMulFloat-13]
	_ = x[OpMulBool-14]
	_ = x[OpDiv-15]
	_ = x[OpDivInt-16]
	_ = x[OpDivFloat-17]
	_ = x[OpDivBool-18]
	_ = x[OpMod-19]
	_ = x[OpModInt-20]
	_ = x[OpModFloat-21]
	_ = x[OpModBool-22]
	_ = x[OpAnd-23]
	_ = x[OpOr-24]
	_ = x[OpNot-25]
	_ = x[OpEqual-26]
	_ = x[OpNotEqual-27]
	_ = x[OpIdentical-28]
	_ = x[OpNotIdentical-29]
	_ = x[OpGreater-30]
	_ = x[OpLess-31]
	_ = x[OpGreaterOrEqual-32]
	_ = x[OpLessOrEqual-33]
	_ = x[OpCompare-34]
	_ = x[OpArrayFetch-35]
	_ = x[OpConcat-36]
	_ = x[_opOneOperand-36]
	_ = x[OpAssertType-37]
	_ = x[OpAssign-38]
	_ = x[OpAssignAdd-39]
	_ = x[OpAssignSub-40]
	_ = x[OpAssignMul-41]
	_ = x[OpAssignDiv-42]
	_ = x[OpAssignMod-43]
	_ = x[OpArrayPut-44]
	_ = x[OpArrayPush-45]
	_ = x[OpCast-46]
	_ = x[OpPreIncrement-47]
	_ = x[OpPostIncrement-48]
	_ = x[OpPreDecrement-49]
	_ = x[OpPostDecrement-50]
	_ = x[OpLoad-51]
	_ = x[OpConst-52]
	_ = x[OpJump-53]
	_ = x[OpJumpZ-54]
	_ = x[OpJumpNZ-55]
	_ = x[_opTwoOperand-55]
	_ = x[OpCall-56]
}

const _Operator_name = "NOOPRETURNADDADD_INTADD_FLOATADD_ARRAYADD_BOOLSUBSUB_INTSUB_FLOATSUB_BOOLMULMUL_INTMUL_FLOATMUL_BOOLDIVDIV_INTDIV_FLOATDIV_BOOLMODMOD_INTMOD_FLOATMOD_BOOLANDORNOTEQUALNOT_EQUALIDENTICALNOT_IDENTICALGTLTGTELTECOMPAREARRAY_FETCHCONCATASSERT_TYPEASSIGNASSIGN_ADDASSIGN_SUBASSIGN_MULASSIGN_DIVASSIGN_MODARRAY_PUTARRAY_PUSHCASTPRE_INCPOST_INCPRE_DECPOST_DECLOADCONSTJUMPJUMP_ZJUMP_NZCALL"

var _Operator_index = [...]uint16{0, 4, 10, 13, 20, 29, 38, 46, 49, 56, 65, 73, 76, 83, 92, 100, 103, 110, 119, 127, 130, 137, 146, 154, 157, 159, 162, 167, 176, 185, 198, 200, 202, 205, 208, 215, 226, 232, 243, 249, 259, 269, 279, 289, 299, 308, 318, 322, 329, 337, 344, 352, 356, 361, 365, 371, 378, 382}

func (i Operator) String() string {
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
