// Code generated by "stringer -type=Operator -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNoop-0]
	_ = x[OpReturn-1]
	_ = x[OpAdd-2]
	_ = x[OpAddInt-3]
	_ = x[OpAddFloat-4]
	_ = x[OpAddArray-5]
	_ = x[OpAddBool-6]
	_ = x[OpSub-7]
	_ = x[OpSubInt-8]
	_ = x[OpSubFloat-9]
	_ = x[OpSubBool-10]
	_ = x[OpMul-11]
	_ = x[OpMulInt-12]
	_ = x[OpMulFloat-13]
	_ = x[OpMulBool-14]
	_ = x[OpDiv-15]
	_ = x[OpDivInt-16]
	_ = x[OpDivFloat-17]
	_ = x[OpDivBool-18]
	_ = x[OpMod-19]
	_ = x[OpModInt-20]
	_ = x[OpModFloat-21]
	_ = x[OpModBool-22]
	_ = x[OpEqual-23]
	_ = x[OpNotEqual-24]
	_ = x[OpIdentical-25]
	_ = x[OpNotIdentical-26]
	_ = x[OpGreater-27]
	_ = x[OpLess-28]
	_ = x[OpGreaterOrEqual-29]
	_ = x[OpLessOrEqual-30]
	_ = x[OpCompare-31]
	_ = x[OpArrayFetch-32]
	_ = x[OpConcat-33]
	_ = x[_opOneOperand-33]
	_ = x[OpAssertType-34]
	_ = x[OpAssign-35]
	_ = x[OpAssignAdd-36]
	_ = x[OpAssignSub-37]
	_ = x[OpAssignMul-38]
	_ = x[OpAssignDiv-39]
	_ = x[OpAssignMod-40]
	_ = x[OpArrayPut-41]
	_ = x[OpArrayPush-42]
	_ = x[OpCast-43]
	_ = x[OpPreIncrement-44]
	_ = x[OpPostIncrement-45]
	_ = x[OpPreDecrement-46]
	_ = x[OpPostDecrement-47]
	_ = x[OpLoad-48]
	_ = x[OpConst-49]
	_ = x[OpJump-50]
	_ = x[OpJumpZ-51]
	_ = x[OpJumpNZ-52]
	_ = x[OpCall-53]
}

const _Operator_name = "NOOPRETURNADDADD_INTADD_FLOATADD_ARRAYADD_BOOLSUBSUB_INTSUB_FLOATSUB_BOOLMULMUL_INTMUL_FLOATMUL_BOOLDIVDIV_INTDIV_FLOATDIV_BOOLMODMOD_INTMOD_FLOATMOD_BOOLEQUALNOT_EQUALIDENTICALNOT_IDENTICALGTLTGTELTECOMPAREARRAY_FETCHCONCATASSERT_TYPEASSIGNASSIGN_ADDASSIGN_SUBASSIGN_MULASSIGN_DIVASSIGN_MODARRAY_PUTARRAY_PUSHCASTPRE_INCPOST_INCPRE_DECPOST_DECLOADCONSTJUMPJUMP_ZJUMP_NZCALL"

var _Operator_index = [...]uint16{0, 4, 10, 13, 20, 29, 38, 46, 49, 56, 65, 73, 76, 83, 92, 100, 103, 110, 119, 127, 130, 137, 146, 154, 159, 168, 177, 190, 192, 194, 197, 200, 207, 218, 224, 235, 241, 251, 261, 271, 281, 291, 300, 310, 314, 321, 329, 336, 344, 348, 353, 357, 363, 370, 374}

func (i Operator) String() string {
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
