// Code generated by "stringer -type=Operator -linecomment"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNoop-0]
	_ = x[OpPop-1]
	_ = x[OpReturn-2]
	_ = x[OpReturnValue-3]
	_ = x[OpAdd-4]
	_ = x[OpSub-5]
	_ = x[OpMul-6]
	_ = x[OpDiv-7]
	_ = x[OpMod-8]
	_ = x[OpPow-9]
	_ = x[OpBwAnd-10]
	_ = x[OpBwOr-11]
	_ = x[OpBwXor-12]
	_ = x[OpBwNot-13]
	_ = x[OpShiftLeft-14]
	_ = x[OpShiftRight-15]
	_ = x[OpEqual-16]
	_ = x[OpNotEqual-17]
	_ = x[OpIdentical-18]
	_ = x[OpNotIdentical-19]
	_ = x[OpNot-20]
	_ = x[OpGreater-21]
	_ = x[OpLess-22]
	_ = x[OpGreaterOrEqual-23]
	_ = x[OpLessOrEqual-24]
	_ = x[OpCompare-25]
	_ = x[OpArrayInit-26]
	_ = x[OpArrayLookup-27]
	_ = x[OpArrayInsert-28]
	_ = x[OpArrayPush-29]
	_ = x[OpConcat-30]
	_ = x[_opOneOperand-30]
	_ = x[OpAssertType-31]
	_ = x[OpAssign-32]
	_ = x[OpAssignAdd-33]
	_ = x[OpAssignSub-34]
	_ = x[OpAssignMul-35]
	_ = x[OpAssignDiv-36]
	_ = x[OpAssignMod-37]
	_ = x[OpAssignPow-38]
	_ = x[OpAssignBwAnd-39]
	_ = x[OpAssignBwOr-40]
	_ = x[OpAssignBwXor-41]
	_ = x[OpAssignConcat-42]
	_ = x[OpAssignShiftLeft-43]
	_ = x[OpAssignShiftRight-44]
	_ = x[OpCast-45]
	_ = x[OpPreIncrement-46]
	_ = x[OpPostIncrement-47]
	_ = x[OpPreDecrement-48]
	_ = x[OpPostDecrement-49]
	_ = x[OpLoad-50]
	_ = x[OpLoadRef-51]
	_ = x[OpConst-52]
	_ = x[OpJump-53]
	_ = x[OpJumpTrue-54]
	_ = x[OpJumpFalse-55]
	_ = x[OpCall-56]
	_ = x[OpEcho-57]
	_ = x[OpIsSet-58]
}

const _Operator_name = "NOOPPOPRETURNRETURN_VALADDSUBMULDIVMODPOWBW_ANDBW_ORBW_XORBW_NOTLSHIFTRSHIFTEQUALNOT_EQUALIDENTICALNOT_IDENTICALNOTGTLTGTELTECOMPAREARRAY_INITARRAY_LOOKUPARRAY_INSERTARRAY_PUSHCONCATASSERT_TYPEASSIGNASSIGN_ADDASSIGN_SUBASSIGN_MULASSIGN_DIVASSIGN_MODASSIGN_POWASSIGN_BW_ANDASSIGN_BW_ORASSIGN_BW_XORASSIGN_CONCATASSIGN_LSHIFTASSIGN_RSHIFTCASTPRE_INCPOST_INCPRE_DECPOST_DECLOADLOAD_REFCONSTJUMPJUMP_TRUEJUMP_FALSECALLECHOISSET"

var _Operator_index = [...]uint16{0, 4, 7, 13, 23, 26, 29, 32, 35, 38, 41, 47, 52, 58, 64, 70, 76, 81, 90, 99, 112, 115, 117, 119, 122, 125, 132, 142, 154, 166, 176, 182, 193, 199, 209, 219, 229, 239, 249, 259, 272, 284, 297, 310, 323, 336, 340, 347, 355, 362, 370, 374, 382, 387, 391, 400, 410, 414, 418, 423}

func (i Operator) String() string {
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
